const LIFECYCLE_STATES = Object.freeze({
  RECEIVED: 'RECEIVED',
  PLANNING: 'PLANNING',
  AWAITING_APPROVAL: 'AWAITING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  EXECUTION_REQUESTED: 'EXECUTION_REQUESTED',
  EXECUTING: 'EXECUTING',
  EXECUTED: 'EXECUTED',
  EVIDENCE_FINALIZED: 'EVIDENCE_FINALIZED',
  CLOSED: 'CLOSED',
  FAILED: 'FAILED'
});

const ALLOWED_TRANSITIONS = Object.freeze({
  [LIFECYCLE_STATES.RECEIVED]: [LIFECYCLE_STATES.PLANNING, LIFECYCLE_STATES.FAILED],
  [LIFECYCLE_STATES.PLANNING]: [
    LIFECYCLE_STATES.AWAITING_APPROVAL,
    LIFECYCLE_STATES.REJECTED,
    LIFECYCLE_STATES.FAILED
  ],
  [LIFECYCLE_STATES.AWAITING_APPROVAL]: [
    LIFECYCLE_STATES.APPROVED,
    LIFECYCLE_STATES.REJECTED,
    LIFECYCLE_STATES.FAILED
  ],
  [LIFECYCLE_STATES.APPROVED]: [
    LIFECYCLE_STATES.EXECUTION_REQUESTED,
    LIFECYCLE_STATES.FAILED
  ],
  [LIFECYCLE_STATES.REJECTED]: [LIFECYCLE_STATES.CLOSED],
  [LIFECYCLE_STATES.EXECUTION_REQUESTED]: [
    LIFECYCLE_STATES.EXECUTING,
    LIFECYCLE_STATES.FAILED
  ],
  [LIFECYCLE_STATES.EXECUTING]: [
    LIFECYCLE_STATES.EXECUTED,
    LIFECYCLE_STATES.FAILED
  ],
  [LIFECYCLE_STATES.EXECUTED]: [
    LIFECYCLE_STATES.EVIDENCE_FINALIZED,
    LIFECYCLE_STATES.FAILED
  ],
  [LIFECYCLE_STATES.EVIDENCE_FINALIZED]: [LIFECYCLE_STATES.CLOSED],
  [LIFECYCLE_STATES.CLOSED]: [],
  [LIFECYCLE_STATES.FAILED]: []
});

function isKnownLifecycleState(state) {
  return Object.values(LIFECYCLE_STATES).includes(state);
}

function isAllowedTransition(previousState, nextState) {
  return Boolean(ALLOWED_TRANSITIONS[previousState] || []).includes(nextState);
}

module.exports = {
  ALLOWED_TRANSITIONS,
  LIFECYCLE_STATES,
  isAllowedTransition,
  isKnownLifecycleState
};
