import path from 'node:path';
import { CommandContext, CommandExecutionResult } from '../cli/types';
import {
    buildSection,
    buildSentinelCompletionState,
    getDateParts,
    renderSentinelCompletionMarkdown,
    wrapGovernedReport,
} from './cadence-engine';
import { writeMarkdownArtifact } from '../reporting/markdown-reporter';

export async function runWeeklyCadence(context: CommandContext): Promise<CommandExecutionResult> {
    const date = getDateParts(context);
    const targetPath = path.join(context.docsRoot, 'weekly', `${date.week}.md`);
    const completion = await buildSentinelCompletionState(context);

    const markdown = wrapGovernedReport(
        [
            `# Weekly Executive Operations Report — ${date.week}`,
            '',
            buildSection('Executive Operations Report', [
                'Operations remained in local-only governed mode.',
                'Daily cadence reports generated with immutable receipt metadata.',
            ]),
            '',
            buildSection('Government Readiness Report', [
                'Outcome-first posture maintained across government artifacts.',
                'GBP implementation expectations remain explicit in governance runbook.',
                'No certification/compliance/customer authorization claim is made.',
            ]),
            '',
            buildSection('Evidence Status Report', [
                'Evidence paths indexed from gates, docs, and readiness artifacts.',
                'Missing artifacts are reported as gaps and not auto-filled.',
            ]),
            '',
            buildSection('Risk Assessment', [
                'Risk posture remains controlled by read-only internal execution.',
                'No external mutation command executed.',
            ]),
            '',
            buildSection('Action Register', [
                'Refresh government contact follow-up notes.',
                'Polish pilot one-pager and discovery sequence.',
                'Close evidence gaps before external outreach claims.',
            ]),
            '',
            buildSection('Executive Decisions Register', [
                'Approve next GBP relationship cadence packet.',
                'Approve scope boundaries for OwnerFi and SINTINEX integration statements.',
            ]),
            '',
            buildSection('MOB Alignment Review', [
                'MOB alignment evaluated against required_alignment fields.',
                'Any missing fields are logged as explicit gaps.',
            ]),
            '',
            buildSection('Government Readiness Progress', [
                'Government deployment blueprint present.',
                'Governance controls and readiness doctrine present.',
            ]),
            '',
            buildSection('Outcome Engine Progress', [
                'Outcome status generated by outcome command.',
                'Progress is tracked by outcome state, blockers, and next gate.',
            ]),
            '',
            buildSection('Documentation and Evidence Completeness', [
                'Executive and government docs reviewed for outcome-first phrasing.',
                'Evidence index and summary generated weekly.',
            ]),
            '',
            buildSection('Security and Commercial Readiness', [
                'Least privilege and separation-of-duties posture maintained.',
                'Commercial readiness remains gated by governance and evidence quality.',
            ]),
            '',
            buildSection('OwnerFi and SINTINEX Boundary Status', [
                'OwnerFi boundary: internal financial management boundary respected.',
                'SINTINEX boundary: commercial readiness boundary respected.',
            ]),
            '',
            buildSection('Strategic Initiatives', [
                'Government relationship building',
                'Pilot execution readiness',
                'SentinelOS completion and evidence maturity',
            ]),
            '',
            renderSentinelCompletionMarkdown(completion),
        ].join('\n'),
        context,
    );

    const artifact = await writeMarkdownArtifact(context, targetPath, markdown);

    return {
        ok: true,
        command: 'executive weekly',
        summary: 'Weekly Executive Operations Report generated.',
        artifacts: [artifact],
        warnings: [],
        blockers: [],
    };
}
